
CREATE DATABASE CAFETERIA

CREATE TABLE TB_CATEGORIA
(
COD_CATEGORIA SMALLINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CATEGORIA VARCHAR(30) NOT NULL
)
GO

CREATE TABLE TB_PRODUTO
(
COD_PRODUTO INT IDENTITY(1,1) NOT NULL,
DESCRICAO VARCHAR(40) NOT NULL,
VALOR_CUSTO DECIMAL(10,2) NOT NULL,
VALOR_VENDA DECIMAL(10,2) NOT NULL,
DATA_CADASTRO SMALLDATETIME NOT NULL,
REFERENCIA VARCHAR(20) NULL,
SITUACAO CHAR(1) NOT NULL, --A(TIVO) / I(NATIVO)
COD_CATEGORIA SMALLINT NOT NULL
)

ALTER TABLE TB_PRODUTO ADD CONSTRAINT PK_TB_PRODUTO PRIMARY KEY (COD_PRODUTO)


ALTER TABLE TB_PRODUTO ADD CONSTRAINT FK_PROD_CATEGORIA FOREIGN KEY (COD_CATEGORIA)
REFERENCES TB_CATEGORIA(COD_CATEGORIA)


CREATE TABLE TB_CLIENTE
(
COD_CLIENTE INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(30) NULL,
SITUACAO CHAR(1) NOT NULL, -- A(TIVO) / I(NATIVO)
DATA_CADASTRO SMALLDATETIME NOT NULL
)


CREATE TABLE TB_PEDIDO
(
COD_PEDIDO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
COD_CLIENTE INT NOT NULL,
DATA_PEDIDO SMALLDATETIME NOT NULL,
VALOR_TOTAL DECIMAL(10,2) NOT NULL
)


ALTER TABLE TB_PEDIDO ADD CONSTRAINT FK_PED_CLIENTE FOREIGN KEY (COD_CLIENTE)
REFERENCES TB_CLIENTE(COD_CLIENTE)


CREATE TABLE TB_PEDIDO_ITEM
(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
COD_PEDIDO INT NOT NULL,
COD_PRODUTO INT NOT NULL,
QUANTIDADE SMALLINT NOT NULL,
VALOR_UNITARIO DECIMAL(10,2)
)

ALTER TABLE TB_PEDIDO_ITEM ADD CONSTRAINT FK_PEDITEM_PED FOREIGN KEY (COD_PEDIDO)
REFERENCES TB_PEDIDO(COD_PEDIDO)

ALTER TABLE TB_PEDIDO_ITEM ADD CONSTRAINT FK_PEDITEM_PROD FOREIGN KEY (COD_PRODUTO)
REFERENCES TB_PRODUTO(COD_PRODUTO)

CREATE UNIQUE NONCLUSTERED INDEX IDX_PED_PROD ON TB_PEDIDO_ITEM (COD_PEDIDO, COD_PRODUTO)



INSERT INTO TB_CATEGORIA VALUES ('Bebidas')
INSERT INTO TB_CATEGORIA VALUES('Alimentos')


INSERT INTO TB_PRODUTO VALUES ('Cafe',2.5,4.5,getdate(),NULL,'A',1)
INSERT INTO TB_PRODUTO VALUES ('Capuccino',2,8,getdate(),NULL,'A',1)
INSERT INTO TB_PRODUTO VALUES ('Mocaccino',6,10,getdate(),NULL,'A',1)
INSERT INTO TB_PRODUTO VALUES ('Gourmet',2,10.5,getdate(),NULL,'A',1)
INSERT INTO TB_PRODUTO VALUES ('Cupcake',8,15,getdate(),NULL,'A',2)
INSERT INTO TB_PRODUTO VALUES ('Brownie',8,12,getdate(),NULL,'A',2)

INSERT INTO TB_CLIENTE VALUES('Paulo Garcia', 'paulo@clientecafe.com.br','A',GETDATE())
INSERT INTO TB_CLIENTE VALUES('Jorge Jr', 'jorgejr@clientecafe.com.br','A',GETDATE())

INSERT INTO TB_PEDIDO VALUES (1,getdate(),68)--1,3,5
INSERT INTO TB_PEDIDO VALUES (2,getdate(),140)--5,6

INSERT INTO TB_PEDIDO_ITEM VALUES (1,1,2,5.0)
INSERT INTO TB_PEDIDO_ITEM VALUES (1,3,1,15.0)
INSERT INTO TB_PEDIDO_ITEM VALUES (1,5,1,15.0)

INSERT INTO TB_PEDIDO_ITEM VALUES (2,5,1,15.0)
INSERT INTO TB_PEDIDO_ITEM VALUES (2,6,1,12.0)


SELECT PED.COD_PEDIDO,C.NOME AS NOME_CLIENTE,PED.DATA_PEDIDO,PROD.COD_PRODUTO,
PROD.DESCRICAO,CAT.CATEGORIA,I.QUANTIDADE,I.VALOR_UNITARIO
FROM TB_PEDIDO PED
INNER JOIN TB_PEDIDO_ITEM I ON PED.COD_PEDIDO = I.COD_PEDIDO
INNER JOIN TB_PRODUTO PROD ON I.COD_PRODUTO = PROD.COD_PRODUTO
INNER JOIN TB_CLIENTE C ON PED.COD_CLIENTE = C.COD_CLIENTE
INNER JOIN TB_CATEGORIA CAT ON PROD.COD_CATEGORIA = CAT.COD_CATEGORIA





